In [7]:
import pandas as pd

df = pd.read_csv(r"c:\Users\Adesola Badmos\OneDrive\Documents\Project 2\ai_job_impact_dataset.csv")

df.head()

,worker_id,country,continent,year,age,gender,education_level,industry,job_role,years_experience,...,training_hours,reskilling_completed,automation_probability,job_satisfaction,promotion_probability,layoff_probability,employment_status_after_ai,annual_performance_rating,mental_stress_score,innovation_score
0,1,Bangladesh,Asia,2035,36.0,Male,Bachelor,Energy,Energy Auditor,7.0,...,136.0,No,0.4382,8.01,0.5516,0.1362,Employed,4.16,23.29,46.19
1,2,Denmark,Europe,2035,58.0,Male,Bachelor,Transportation,Aviation Mechanic,13.0,...,55.5,Yes,0.4848,8.00,0.4824,0.2122,Employed,3.65,19.45,59.25
2,3,Nigeria,Africa,2035,59.0,Female,High School,IT,DevOps Engineer,34.0,...,110.8,No,0.4564,6.11,0.3561,0.1431,Employed,3.42,47.87,16.69
3,4,Vietnam,Asia,2035,54.0,Female,Bachelor,Manufacturing,Production Supervisor,21.0,...,109.7,Yes,0.6871,5.64,0.3547,0.2724,Employed,3.77,38.92,39.84
4,5,Mexico,North America,2034,54.0,Female,Bachelor,Retail,Inventory Manager,13.0,...,71.3,Yes,0.3714,9.68,0.4796,0.1333,Employed,3.79,27.33,47.53

In [8]:
df.tail()

,worker_id,country,continent,year,age,gender,education_level,industry,job_role,years_experience,...,training_hours,reskilling_completed,automation_probability,job_satisfaction,promotion_probability,layoff_probability,employment_status_after_ai,annual_performance_rating,mental_stress_score,innovation_score
99995,99996,France,Europe,2022,27.0,Male,Bachelor,Media,Journalist,5.0,...,101.1,Yes,NaN,7.45,0.4649,0.0000,Employed,4.03,32.94,63.05
99996,99997,Japan,Asia,2027,57.0,Male,Master,Manufacturing,Robotics Technician,13.0,...,63.9,No,0.6149,7.79,0.5786,0.4566,Career Change,4.09,47.22,54.24
99997,99998,India,Asia,2027,23.0,Female,High School,Hospitality,Travel Agent,NaN,...,72.2,Yes,0.3016,6.55,0.1554,0.2086,Employed,1.31,25.87,0.00
99998,99999,Brazil,South America,2024,35.0,Male,Diploma,Media,Social Media Manager,8.0,...,48.3,No,0.2649,7.62,0.4450,0.1198,Employed,2.76,42.57,59.79
99999,100000,Kenya,Africa,2032,20.0,Female,Bachelor,Energy,Energy Policy Analyst,0.0,...,105.1,No,0.3686,7.54,0.4471,0.1147,Reskilled,3.54,30.64,50.65

# Data Inspection

In [ ]:
# Inspecting all data columns

df.columns.tolist()

['worker_id',
 'country',
 'continent',
 'year',
 'age',
 'gender',
 'education_level',
 'industry',
 'job_role',
 'years_experience',
 'salary_usd',
 'employment_type',
 'company_size',
 'remote_work',
 'ai_adoption_level',
 'ai_literacy_score',
 'digital_skill_score',
 'productivity_score',
 'hours_worked_per_week',
 'training_hours',
 'reskilling_completed',
 'automation_probability',
 'job_satisfaction',
 'promotion_probability',
 'layoff_probability',
 'employment_status_after_ai',
 'annual_performance_rating',
 'mental_stress_score',
 'innovation_score']

In [24]:
# countries and their value check

df['country'].value_counts()

country
India             6437
USA               6386
China             5397
Indonesia         3231
UK                3163
France            2776
Germany           2753
Nigeria           2739
Philippines       2727
Canada            2700
Japan             2683
South Korea       2313
Brazil            2276
Vietnam           2273
Egypt             2260
South Africa      2243
Italy             2237
Saudi Arabia      1856
Thailand          1839
Kenya             1832
UAE               1828
Netherlands       1822
Malaysia          1809
Argentina         1800
Turkey            1794
Mexico            1780
Australia         1779
Israel            1750
Spain             1750
Ghana             1436
Singapore         1428
Chile             1420
Bangladesh        1406
Switzerland       1406
Pakistan          1357
Morocco           1355
Colombia          1325
Sweden            1297
Poland             936
Greece             936
New Zealand        930
Finland            930
Ireland            926
Denmark            916
Peru               910
Austria            908
Norway             866
Belgium            864
Portugal           858
Hungary            479
Romania            459
Czech Republic     419
Name: count, dtype: int64

In [ ]:
# A distinct count of all countries
df["country"].nunique()

52

In [25]:
df.nunique()

worker_id                     99501
country                          52
continent                         6
year                             16
age                              48
gender                            3
education_level                   5
industry                         15
job_role                        298
years_experience                 47
salary_usd                    96935
employment_type                   4
company_size                      4
remote_work                       2
ai_adoption_level              8471
ai_literacy_score              9494
digital_skill_score            8570
productivity_score             8459
hours_worked_per_week           542
training_hours                 1683
reskilling_completed              2
automation_probability         6912
job_satisfaction                709
promotion_probability          5708
layoff_probability             4642
employment_status_after_ai        4
annual_performance_rating       401
mental_stress_score            5531
innovation_score               9589
dtype: int64

In [27]:
print(df["age"].max())

65.0

In [28]:
print(df["age"].min())

18.0

In [30]:
print(df["age"].mean())

41.450654772233165

In [ ]:
# Checking for missing values

df = df.isnull().sum()

In [ ]:
# Checking for duplicate values

df = df.duplicated().sum()